# -*- coding: utf-8 -*-
"""FInal_ensemble_file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CT5P_UfS33MLRnz59P-IyvWQr3RmzzUP

##Link Extractor Method
"""

!sudo apt-get install tesseract-ocr
!pip install pytesseract
import cv2
import pytesseract as tess
import numpy as np
!pip install urlextract
from urlextract import URLExtract


def lin_ex(file_path):
  # FILE_PATH = file_path 
  img= cv2.imread(file_path)
  gray_img= cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
  gray_img, img_bin= cv2.threshold(gray_img,128,255,cv2.THRESH_BINARY | cv2.THRESH_OTSU)
  gray_img = cv2.bitwise_not(img_bin)
  kernel = np.ones((2, 1), np.uint8)
  img = cv2.erode(gray_img, kernel, iterations=1)
  img = cv2.dilate(img, kernel, iterations=1)
  # print(type(img), 'this is type(img)')
  out_below = tess.image_to_string(img)
  extractor = URLExtract()
  urls = extractor.find_urls(out_below)
  return urls

"""##Number Extracting Method """

!pip install git+https://github.com/faustomorales/keras-ocr.git#egg=keras-ocr
!pip install keras-ocr
import keras_ocr
import cv2
def num_data(path):
  pipeline = keras_ocr.pipeline.Pipeline()
  # path= "/content/Screenshot_20221117_102401.png"
  pred= pipeline.recognize([keras_ocr.tools.read(path)])
  pred1= pred[0]
  data=[]
  box1=[]
  for text,box in pred1:
    data.append(text)
  lis=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety','hundred','thousand','lakh','crore','arab','million','billion','trillion']
  num= []
  for word in data:
    if word in lis:
      num.append(word)
  return num

"""##the 'Main' File"""

def main(file_path):
  url = lin_ex(file_path) 
  numeric_data = num_data(file_path)
  return url,numeric_data